sudo: required

language: generic

services:
  - docker

before_install:
  - echo "START CREATING AN IMAGE WITH DOCKERFILE"
  - docker build -t glory/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true glory/docker-react-app npm run test -- --coverage

after_success:
  - echo "TEST SUCCESS"
